repos:
- repo: meta
  hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.37.1
  hooks:
    - id: check-github-workflows
- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
    - id: pyupgrade
      args: ["--py310-plus"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.12
  hooks:
    - id: ruff-check
      types_or: [ python ]
      args: [ --select, I ]
    - id: ruff-check
      types_or: [ python ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python ]
