ARG PYTHON_VERSION="3.8"
FROM python:${PYTHON_VERSION}
RUN mkdir /opt/compute
RUN pip install kubernetes
RUN pip install --no-binary :all: --force-reinstall pyzmq

COPY sdk /opt/compute/sdk/
WORKDIR /opt/compute/sdk
RUN pip install .

COPY endpoint /opt/compute/endpoint
WORKDIR /opt/compute/endpoint
RUN pip install .

RUN useradd -m compute
RUN mkdir -p /home/compute/.kube
USER compute
WORKDIR /home/compute
COPY helm/boot.sh .
ENV HOME /home/compute
