engine:
    type: GlobusComputeEngine
    max_workers_per_node: 2
    worker_debug: False

    address:
        type: address_by_interface
        ifname: ib0

    provider:
        type: SlurmProvider
        partition: {{ PARTITION }}  # e.g., bdws
        launcher:
          type: SrunLauncher

        # Command to be run before starting a worker
        # e.g., "module load anaconda; source activate gce_env"
        worker_init: {{ COMMAND }}

        nodes_per_block: 1
        init_blocks: 0
        min_blocks: 0
        max_blocks: 1
        walltime: 00:30:00
