name: Canary

run-name: "Canary (${{ github.event_name != 'workflow_dispatch' && 'production' || format('{0}{1}', github.event.inputs.environment, github.event.inputs.pd_test != '' && format(' [no test, just PD: {0}]', github.event.inputs.pd_test) || '') }})"

on:
  # Start the first run at 3 min past the hour as GitHub is more likely to skip runs
  # at the top of the hour (minute 0)
  schedule:
    - cron: "3/5 * * * *"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Target environment"
        required: true
        default: "production"
        options:
          - sandbox
          - integration
          - test
          - preview
          - staging
          - production

      pd_test:
        type: choice
        description: "Don't run infrastructure test; just invoke PagerDuty's API"
        required: true
        default: ""
        options:
          - ""
          - "signal success"
          - "signal failure"


jobs:
  canary:
    timeout-minutes: 4
    runs-on: ubuntu-slim
    steps:
      - name: "Only 'production' currently handled ..."
        if: github.event_name == 'workflow_dispatch' && inputs.environment != 'production'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            gh run cancel --repo globus/globus-compute ${{ github.run_id }}

      - uses: actions/checkout@v6
        with:
          ref: main

      - uses: astral-sh/setup-uv@v2
        with:
            enable-cache: true

      - name: "Calculate Canary Cache Key"
        if: inputs.pd_test == ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            CANARY_CACHE_KEY="canary_incident_${{ github.event.inputs.environment }}"

            echo "Computed CANARY_CACHE_KEY=${CANARY_CACHE_KEY}"

            # export for later steps
            echo "CANARY_CACHE_KEY=${CANARY_CACHE_KEY}" >> "$GITHUB_ENV"
            echo "CANARY_CACHE_KEY=${CANARY_CACHE_KEY}" >> "$GITHUB_OUTPUT"

      - name: "Install Globus Compute SDK"
        if: inputs.pd_test == ''
        run: |
          uv venv
          uv pip install -U pip setuptools
          uv pip install globus-compute-sdk

      - name: "Test Kernel: Executor.submit() a task"
        if: inputs.pd_test == ''
        env:
          GLOBUS_COMPUTE_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
          GLOBUS_COMPUTE_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
        run: |
          uv run python << 'EOF'
          # Python script; submit task to tutorial endpoint via Executor
          import random
          from globus_compute_sdk import Executor

          def double(x: float | int) -> float | int:
              return 2 * x

          tut_endpoint_id = "4b116d3c-1703-4f8f-9f6f-39921e5864df"
          inp_value = random.randint(-2**30, 2**30)
          exp_value = 2 * inp_value
          with Executor(tut_endpoint_id) as ex:
              f = ex.submit(double, inp_value)
              res = f.result(timeout=60)
              assert res == exp_value
          EOF

      - name: "PD Signaling Test"
        if: inputs.pd_test != ''
        run: |
          [[ "signal failure" = "${{ inputs.pd_test }}" ]] && exit 1
          exit 0

      - name: "Notify PagerDuty"
        if: ${{ !cancelled() }}
        run: |
          curl -X POST 'https://events.pagerduty.com/v2/enqueue' \
            -H 'Content-Type: application/json' \
            --data '{
              "routing_key": "${{ secrets.PAGERDUTY_ROUTING_KEY }}",
              "dedup_key": "end_to_end_compute_service_status-${{ env.CANARY_CACHE_KEY }}",
              "event_action": "${{ job.status == 'success' && 'resolve' || 'trigger' }}",
              "payload": {
                "summary": "Compute Service Not Processing Jobs",
                "severity": "critical",
                "source": "Compute Services Canary Tester",
                "custom_details": {
                  "repository": "${{ github.repository }}",
                  "branch": "${{ github.ref }}",
                  "commit": "${{ github.sha }}",
                  "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "AlarmName": "production-canary"
                }
              }
            }'
